# Generated by Django 3.1.3 on 2022-12-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='', help_text='How many items are currently in stock', max_length=20, unique=True, verbose_name='Stock Keeping Unit'),
        ),
    ]
